server:
  port: 8080

userinfo:
  name: yor
  phone: 654321
spring:
  datasource:
    url: jdbc:mysql://bdm25056535.my3w.com:3306/bdm25056535_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: bdm25056535
    password: password
    driver-class-name: com.mysql.jdbc.Driver