spring:
  profiles:
#    active: dev
    active: prd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
