server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://bdm25056535.my3w.com:3306/bdm25056535_db?useUnicode=true&characterEncoding=utf-8
      username: bdm25056535
      password: password

swagger:
  show : false